### ISSUE TITLE
Attempting to register an unknown factory: `validator:card-number`

### ISSUE THREAD

**Issue by thoresuenert** [offirgolan/ember-cp-validations#107]
Hello,
after running the generator: ember g validator card-number the unit test fails with: 
```
Promise rejected before it works: Attempting to register an unknown factory: `validator:card-number`@ 9 ms
Source: 	
TypeError: Attempting to register an unknown factory: `validator:card-number`
    at Object.Registry.register (http://localhost:4200/assets/vendor.js:12404:15)
    at Klass._setupIsolatedContainer (http://localhost:4200/assets/test-support.js:7079:29)
    at Klass.setupContainer (http://localhost:4200/assets/test-support.js:6918:14)
    at http://localhost:4200/assets/test-support.js:6905:21
    at Object.initializePromise (http://localhost:4200/assets/vendor.js:63487:7)
    at new Promise (http://localhost:4200/assets/vendor.js:65337:21)
    at nextStep (http://localhost:4200/assets/test-support.js:6904:18)
    at Klass.invokeSteps (http://localhost:4200/assets/test-support.js:6911:14)
    at Klass.setup (http://localhost:4200/assets/test-support.js:6878:19)
    at Object.setup (http://localhost:4200/assets/test-support.js:6290:23)
```
I am using:
ember 2.3.0-beta.1

with PODs structure and a modulesprefix name.

generated validator is in app/validators/card-number
console.log:
```
factory.js:484 [ember-cp-validations] Validator not found of type: card-number.
```
Anybody can hint me in the right direction to solve this problem?

**Comment by offirgolan** [comment]
Can you please add your test case code?

**Comment by thoresuenert** [comment]
```

**Comment by offirgolan** [comment]
Oh this is right out of the box... interesting. Can you also add your `package.json` and `bower.json`?

**Comment by thoresuenert** [comment]
package.json
```
{
  "name": "meshville-app",
  "version": "0.0.0",
  "description": "Small description for meshville-app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "^2.3.0-beta.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.1",
    "ember-cli-sass-pods": "1.2.0",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cp-validations": "2.2.1",
    "ember-data": "^2.3.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-i18n": "4.2.0",
    "ember-i18n-cp-validations": "2.1.4",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.0.1",
    "ember-simple-auth-token": "1.0.0",
    "torii": "0.6.1"
  }
}
```
bower.json
```
{
  "name": "meshville-app",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

**Comment by offirgolan** [comment]
Hmmm I'm not able to recreate this issue. I created a fresh dummy app with the setup below and ran `ember g validator card-number` and the test passes.

In config/environment.js
```json
{
    modulePrefix: 'meshville-app',
    environment: environment,
    podModulePrefix: 'meshville-app/pods',
    baseURL: '/',
    locationType: 'auto'
}
```

bower.json

```json
{
  "name": "meshville-app",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

package.json

```json
"devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.3.0-beta.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cp-validations": "2.2.1",
    "ember-data": "^2.3.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-i18n": "4.2.0",
    "ember-i18n-cp-validations": "2.1.4",
    "ember-resolver": "^2.0.3"
  }
```

**Comment by thoresuenert** [comment]
I removed:
packages.json
```
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-ic-ajax": "0.2.4",
```
and it is working right now.
I guess it will be the first one which leads to this error.
I dont know why that module is in there, maybe it is needed for ember 2.2

**Comment by offirgolan** [comment]
Ah... `ember-cli-ic-ajax` has been replace by `ember-ajax` and `ember-cli-content-security-policy` was removed in ember-cli 2.2.x.

**Comment by thoresuenert** [comment]
thanks for your time.

**Comment by offirgolan** [comment]
Np! :smiley_cat:
