### ISSUE TITLE
Error creating validator test with blueprint

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#233]
```
ember g validator-test my-validator
version: 2.4.2
Cannot read property 'addonPackages' of undefined
TypeError: Cannot read property 'addonPackages' of undefined
    at Class.module.exports._filesPath (foo/ember2.4-bar/node_modules/ember-cp-validations/blueprints/validator-test/index.js:20:42)
    at Class.Blueprint.files (foo/ember2.4-bar/node_modules/ember-cli/lib/models/blueprint.js:317:24)
    at Class.Blueprint.supportsAddon (foo/ember2.4-bar/node_modules/ember-cli/lib/models/blueprint.js:808:15)
    at Class.module.exports.Task.extend.run (foo/ember2.4-bar/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:25:98)
    at Class.module.exports.Command.extend.run (foo/ember2.4-bar/node_modules/ember-cli/lib/commands/generate.js:65:17)
    at Class.<anonymous> (foo/ember2.4-bar/node_modules/ember-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (foo/ember2.4-bar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (foo/ember2.4-bar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (foo/ember2.4-bar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (foo/ember2.4-bar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

@blimmer

**Comment by blimmer** [comment]
Asked for clarification on a workaround on the [corresponding ember-cli bug](https://github.com/ember-cli/ember-cli/issues/5481)
