### ISSUE TITLE
Lodash isn't available after installing the package

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#3]
I get this error:
```
Error while processing route: forgot.index Could not find module `lodash/array` imported from `ember-cp-validations/utils/validations-factory` Error: Could not find module `lodash/array` imported from `ember-cp-validations/utils/validations-factory`
    at requireFrom (http://localhost:4200/assets/vendor.js:145:13)
    at reify (http://localhost:4200/assets/vendor.js:132:22)
    at mod.state (http://localhost:4200/assets/vendor.js:175:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:56:14)
    at requireModule (http://localhost:4200/assets/vendor.js:174:5)
    at requireFrom (http://localhost:4200/assets/vendor.js:147:12)
    at reify (http://localhost:4200/assets/vendor.js:132:22)
    at mod.state (http://localhost:4200/assets/vendor.js:175:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:56:14)
    at requireModule (http://localhost:4200/assets/vendor.js:174:5)
```

**Comment by zhuolikevin** [comment]
Uhm.....I still got this error after I ran
  ember install ember-cp-validations

**Comment by blimmer** [comment]
We haven't released this fix yet but will later today. For now run `ember g ember-model-validations`

**Comment by offirgolan** [comment]
@zhuolikevin I will be making a release in the next few hours. I just wanted to include #10.

**Comment by offirgolan** [comment]
Just release v1.0.1 which should resolve this issue.
