### ISSUE TITLE
custom validations:- Validator not found of type error on test 

### ISSUE THREAD

**Issue by SatVel** [offirgolan/ember-cp-validations#457]
Hi, 

I have created a custom validator called exceed-capacity and the code for it is as follows

`import BaseValidator from 'ember-cp-validations/validators/base';

const ExceedCapacity = BaseValidator.extend({
  validate(value,options) {
    let capacity=1000;
    if(parseInt(value)>capacity){
      let message="Exceeding Available Capacity"; 
    if(options.message) {
          message = options.message;          
      }
     return message; 
    }    
    else{
    return true;
    }
  }
});

ExceedCapacity.reopenClass({
  getDependentsFor(attribute, options) {
    return [];
  }
});

export default ExceedCapacity;`

I have used the command ember generate validator exceed-capacity for creating the validator (ref:-https://github.com/offirgolan/ember-cp-validations/issues/261)

The exceed-capacity validator  works absolutely fine for me but the tests fail :-(

I get the following error on test

Promise rejected after it exists: [ember-cp-validations] Validator not found of type: exceed-capacity.@ 42 ms
Source: 	
Error: [ember-cp-validations] Validator not found of type: exceed-capacity.
    at lookupValidator (http://localhost:7357/assets/vendor.js:89437:13)
    at http://localhost:7357/assets/vendor.js:89263:92
    at Array.map (native)
    at getCPDependentKeysFor (http://localhost:7357/assets/vendor.js:89259:37)
    at createCPValidationFor (http://localhost:7357/assets/vendor.js:89089:43)
    at http://localhost:7357/assets/vendor.js:89069:22
    at Array.forEach (native)
    at createAttrsClass (http://localhost:7357/assets/vendor.js:89041:27)
    at createValidationsClass (http://localhost:7357/assets/vendor.js:88915:22)
    at Class.<anonymous> (http://localhost:7357/assets/vendor.js:88798:25)

I am using a pod structure 

### Environment

- Ember Version: 2.8.3
- Ember CLI Version: 2.8.0
- Ember CP Validations Version: 3.1.0

**Comment by offirgolan** [comment]
@SatVel in your unit tests, you need to add the validator to the `needs` array.

```js
moduleForModel('user', 'User Model Testing', {
  // Specify the other units that are required for this test.
  needs: ['validator:exceed-capacity']
});
```

**Comment by SatVel** [comment]
@offirgolan :- I included 'validator:exceed-capacity' inside the needs array but unfortunately , the tests still fail. My test file is as follows:-

`import { moduleFor, test } from 'ember-qunit';

moduleFor('validator:exceed-capacity', 'Unit | Validator | exceed-capacity', {
  needs: ['validator:messages', 'validator:exceed-capacity']
});

test('it works', function(assert) {
  var validator = this.subject();
  assert.ok(validator);
});

test('value does not exceed capacity', function(assert) {
    assert.expect(1);

    let validator =  this.subject();
    let done = assert.async();

    validator.validate(100).then((message) => {
      assert.equal(message, true);
      done();
    });
});
`

**Comment by SatVel** [comment]
@offirgolan - Thanks a lot for pointing that out! Adding that to the model test file got rid of the error. However, one of the test that I have written for the exceed-capacity validator fails with the following error message


Unit | Validator | exceed-capacity: value does not exceed capacity (1, 0, 1)Rerun58 ms
Died on test #1     at testWrapper (http://localhost:7357/assets/test-support.js:13639:11)
    at test (http://localhost:7357/assets/test-support.js:13653:39)
    at Module.callback (http://localhost:7357/assets/tests.js:14638:24)
    at Module.exports (http://localhost:7357/assets/vendor.js:132:32)
    at requireModule (http://localhost:7357/assets/vendor.js:32:18)
    at TestLoader.require (http://localhost:7357/assets/test-support.js:13419:7)
    at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:13411:14): validator.validate(...).then is not a function@ 10 ms
Source: 	
TypeError: validator.validate(...).then is not a function
    at Object.<anonymous> (http://localhost:7357/assets/tests.js:14644:29)
    at Object.wrapper (http://localhost:7357/assets/test-support.js:13610:29)
    at runTest (http://localhost:7357/assets/test-support.js:3115:28)
    at Test.run (http://localhost:7357/assets/test-support.js:3100:4)
    at http://localhost:7357/assets/test-support.js:3242:11
    at process (http://localhost:7357/assets/test-support.js:2901:24)
    at begin (http://localhost:7357/assets/test-support.js:2883:2)
    at http://localhost:7357/assets/test-support.js:2943:4

My test code is as follows, The first test passes, the second one fails.
---------------------------------
import { moduleFor, test } from 'ember-qunit';

moduleFor('validator:exceed-capacity', 'Unit | Validator | exceed-capacity', {
  needs: ['validator:messages']
});

test('it works', function(assert) {
  var validator = this.subject();
  assert.ok(validator);
});

test('value does not exceed capacity', function(assert) {
    assert.expect(1);

    let validator =  this.subject();
    let done = assert.async();

    validator.validate(100).then((message) => {
      assert.equal(message, true);
      done();
    });
});

Am I missing something? or doing something wrong?

Thanks and Regards
Satyen

**Comment by offirgolan** [comment]
@SatVel I think this is your issue right here:

```
validator.validate(...).then is not a function@ 10 ms
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
