### ISSUE TITLE
Help with integration test intermittent i18n error

### ISSUE THREAD

**Issue by hadiwina** [offirgolan/ember-cp-validations#625]
This is most likely something that I do, but I can't seem to figure out why.

### Environment

- Ember Version: 2.8
- Ember CLI Version: 2.8
- Ember CP Validations Version: 3.5.4

### Steps to Reproduce

I'm not sure how to reproduce this, but on integration test of a component where I use `ember-cp-vallidations`, I **intermittently** get the following error:

```
TypeError: i18n.exists is not a function
    at Class.getDescriptionFor (http://localhost:4200/assets/supervision.js:26345:26)
    at Class.superWrapper [as getDescriptionFor] (http://localhost:4200/assets/vendor.js:43091:22)
    at Class.createErrorMessage (http://localhost:4200/assets/vendor.js:277282:44)
    at Class.validate (http://localhost:4200/assets/vendor.js:274280:55)
    at http://localhost:4200/assets/vendor.js:275820:26
    at http://localhost:4200/assets/vendor.js:275914:17
    at Array.map (<anonymous>)
    at generateValidationResultsFor (http://localhost:4200/assets/vendor.js:275891:23)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:275819:31)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:275160:19)
```

The integration test looks something like this:

```
test('it raises an error when user select specific and nothing is selected', function(assert) {
    this.setProperties({
        data,
        component: null
    });

    this.render(hbs`{{multi-policy-selector registeredAs=component data=data}}`);

    this.$('[data-test-select-button-value]').eq(1).click();

    assert.ok(this.$('.error-message .alert-danger').hasClass('hidden'), 'Error message is not shown');

    // Test that if nothing is provided, error message shows.
    run(() => this.get('component').isValid());
    assert.ok(!this.$('.error-message .alert-danger').hasClass('hidden'), 'Error message is now shown');

    const filters = Ember.A([
        Ember.Object.create({ id: null, name: 'foo' }),
        Ember.Object.create({ id: '1', name: 'foo/bar/bar' })
    ]);

    // Test that if we save something, error message is hidden again.
    run(() => this.get('component').send('save', filters));
    assert.ok(this.$('.error-message .alert-danger').hasClass('hidden'), 'Error message is not shown');
});
```

I think the bit that causes this issue is `run(() => this.get('component').isValid());`, and this `isValid()` is basically this in the component:

```
isValid() {
    const isValid = this.get('validations.isValid');
    this.set('_hasError', !isValid);
    return isValid;
},
```

I'm not 100% sure but this looks like something is failing within the `ember-cp-validations`. I'm trying to figure this out but not sure where to start. Is there any idea about this error message?

Appreciate the help! 😄

**Comment by hadiwina** [comment]
This is no longer an issue. Thank you!
